#!/bin/bash
## install sbt and git ##
echo "deb http://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
apt-get update
apt-get install -y apt-utils ### FIX warning about 'missing apt-utils'
apt-get install -y --force-yes sbt git openssh-server net-tools
## Reference - https://mahout.apache.org/users/sparkbindings/play-with-shell.html
### 1. Download Apache Spark 1.1.1 and unpack the archive file
cd /opt
wget http://archive.apache.org/dist/spark/spark-1.1.1/spark-1.1.1.tgz
tar zxvf spark-1.1.1.tgz
ln -s /opt/spark-1.1.1 /opt/spark
cd /opt/spark
### 2. Change to the directory where you unpacked Spark and type 'sbt/sbt assembly' to build it 
sbt/sbt assembly
### 3. Create a directory for Mahout somewhere on your machine, change to there and checkout 
###    the master branch of Apache Mahout from GitHub
### 4. Change to the mahout directory and build mahout using mvn -DskipTests clean install
### ----- Jazz's Note: Use Mahout 0.10.0 Release instead
cd /opt
wget http://archive.apache.org/dist/mahout/0.10.0/mahout-distribution-0.10.0.tar.gz
tar zxvf mahout-distribution-0.10.0.tar.gz
ln -s /opt/mahout-distribution-0.10.0 /opt/mahout
### SSH key exchange
cd ~
mkdir -p /root/.ssh
ssh-keygen -P "" -t rsa -f /root/.ssh/id_rsa
cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys
