#!/bin/bash
apt-get -y update
DEBIAN_FRONTEND=noninteractive
apt-get -y -o APT::Immediate-Configure=false install wget
## setup bigtop related apt repository
wget -q http://archive.apache.org/dist/bigtop/bigtop-1.0.0/repos/GPG-KEY-bigtop -O- | apt-key add -
wget -q -O /etc/apt/sources.list.d/bigtop.list http://archive.apache.org/dist/bigtop/bigtop-1.0.0/repos/trusty/bigtop.list
apt-get -y update
## install bigtop related packages
apt-get install -y -q --force-yes --no-install-recommends -o APT::Immediate-Configure=false openjdk-7-jre-headless bigtop-utils hadoop-conf-pseudo net-tools
## enable WebHDFS and append
sed -i 's#</configuration>##' /etc/hadoop/conf/hdfs-site.xml
cat >> /etc/hadoop/conf/hdfs-site.xml << EOF
  <property>
    <name>dfs.webhdfs.enabled</name>
    <value>true</value>
  </property>
  <property>
    <name>dfs.support.append</name>
    <value>true</value>
  </property>
  <property>
    <name>dfs.support.broken.append</name>
    <value>true</value>
  </property>
</configuration>
EOF
## format NameNode
/etc/init.d/hadoop-hdfs-namenode init
## start HDFS
for i in hadoop-hdfs-namenode hadoop-hdfs-datanode ; do service $i start ; done
## initialize HDFS
/usr/lib/hadoop/libexec/init-hdfs.sh
## stop HDFS
for i in hadoop-hdfs-namenode hadoop-hdfs-datanode ; do service $i stop ; done
## clean up
apt-get autoclean
rm -rf /var/lib/apt/lists/*
rm -rf /var/log/hadoop-hdfs/*
