#!/bin/bash
apt-get -y update
apt-get -y install wget
## setup bigtop related apt repository
wget -q http://archive.apache.org/dist/bigtop/bigtop-0.8.0/repos/GPG-KEY-bigtop -O- | apt-key add
wget -q -O /etc/apt/sources.list.d/bigtop.list http://archive.apache.org/dist/bigtop/bigtop-0.8.0/repos/trusty/bigtop.list
apt-get -y update
## install bigtop related packages
apt-get install -y -q --force-yes --no-install-recommends openjdk-7-jre-headless bigtop-utils hadoop-conf-pseudo
## format NameNode
/etc/init.d/hadoop-hdfs-namenode init
## start HDFS
for i in hadoop-hdfs-namenode hadoop-hdfs-datanode ; do service $i start ; done
## initialize HDFS
/usr/lib/hadoop/libexec/init-hdfs.sh
## stop HDFS
for i in hadoop-hdfs-namenode hadoop-hdfs-datanode ; do service $i stop ; done
## clean up
apt-get -y autoremove --purge wget
apt-get clean
rm -rf /var/lib/apt/lists/*
