#!/bin/bash
set -e
/etc/init.d/hadoop-hdfs-namenode restart
/etc/init.d/hadoop-hdfs-datanode restart
/etc/init.d/hadoop-yarn-resourcemanager restart
/etc/init.d/hadoop-yarn-nodemanager restart
/bin/bash
